//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 04:02:04 PM WET 
//


package xmlrest;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import xmlrest.ListCourses.Courses.Materials.Material;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="courses" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="materials" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="material" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courses"
})
@XmlRootElement(name = "ListCourses")
public class ListCourses implements Serializable{

	public ArrayList<HashMap<String,Integer>> toMap(){
		ArrayList<HashMap<String,Integer>> res=new ArrayList<>();
		
		for(Courses c:courses){
			HashMap<String,Integer> map=new HashMap<>();
			
			if(c.getMaterials()==null)
				continue;
			
			for(Material m:c.getMaterials().material){
				map.put("id", (int)m.id);
				map.put("courseid", (int)c.id);
			}
			res.add(map);
		}
		
		
		return res;
	}
	
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected List<ListCourses.Courses> courses;
	
    public ListCourses(){}
    
    public ListCourses.Courses hasCourse(int id){
    	for(ListCourses.Courses c:courses)
    		if(c.getId()==id)
    			return c;
    	return null;
    }
    
    public ListCourses(List<Map> lm){
    	this.courses=new ArrayList<ListCourses.Courses>();
    	
    	for(Map<String,Integer> m:lm){
    		int i=m.get("courseid");
    		byte b;
    		ListCourses.Courses c=hasCourse(i);
    		
    		if(c==null){
    			c=new ListCourses.Courses();
    			c.setId((byte)i);
    			
    			this.courses.add(c);
    		}
    		
    		ListCourses.Courses.Materials ms=new ListCourses.Courses.Materials();
    		
    		ListCourses.Courses.Materials.Material m1=new ListCourses.Courses.Materials.Material();
    		
    		i=m.get("id");
    		
    		b=(byte)i;
    		
    		m1.setId(b);
    		
    		
    		ms.addMaterial(m1);
    	    		
    		c.setMaterials(ms);
    		
    		
    		
    	}
    	
    	
    }
    
    
    public void setCourses(List<ListCourses.Courses> c){
    	this.courses=c;
    }
    
	
	//NOVO
	public ArrayList<Byte> differentCourses(ListCourses lc){
		ArrayList<Byte> res=new ArrayList<>();
		
		int ind;
		ListCourses.Courses aux;
		for(ListCourses.Courses c:lc.courses){
			
			ind=this.courses.indexOf(c);
			if(ind==-1)
				res.add(c.getId());
			else{
				aux=this.courses.get(ind);
				if(!aux.sameMaterials(c))
					res.add(c.getId());
			}	
			
		}
		
		return res;
	}
	
	
	
    /**
     * Gets the value of the courses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListCourses.Courses }
     * 
     * 
     */
    public List<ListCourses.Courses> getCourses() {
        if (courses == null) {
            courses = new ArrayList<ListCourses.Courses>();
        }
        return this.courses;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="materials" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="material" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "materials"
    })
    public static class Courses {

		public boolean equals(Courses other){
			return this.id==other.id;
		}
		
		
		

		//NOVO
		public boolean sameMaterials(Courses c){
			if(this.materials.getMaterial().size()!=c.materials.getMaterial().size())
				return false;
			
			
			
			for(int i=0;i<this.materials.getMaterial().size();i++){
				if(this.materials.getMaterial().get(i).getId()!=c.materials.getMaterial().get(i).getId())
					return false;
			}
			
			return true;
		}

        @XmlElement(required = true)
        protected String name;
        protected ListCourses.Courses.Materials materials;
        @XmlAttribute(name = "id")
        protected Byte id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the materials property.
         * 
         * @return
         *     possible object is
         *     {@link ListCourses.Courses.Materials }
         *     
         */
        public ListCourses.Courses.Materials getMaterials() {
            return materials;
        }

        /**
         * Sets the value of the materials property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListCourses.Courses.Materials }
         *     
         */
        public void setMaterials(ListCourses.Courses.Materials value) {
            this.materials = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setId(Byte value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="material" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "material"
        })
        public static class Materials {

            protected List<ListCourses.Courses.Materials.Material> material;
            
            
            
            /**
             * Gets the value of the material property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the material property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMaterial().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ListCourses.Courses.Materials.Material }
             * 
             * 
             */
            public List<ListCourses.Courses.Materials.Material> getMaterial() {
                if (material == null) {
                    material = new ArrayList<ListCourses.Courses.Materials.Material>();
                }
                return this.material;
            }


            public void addMaterial(ListCourses.Courses.Materials.Material material) {
				if(this.material==null)
					this.material=new ArrayList<ListCourses.Courses.Materials.Material>();
				this.material.add(material);
            
            }


			/**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "title",
                "location"
            })
            public static class Material {

                @XmlElement(required = true)
                protected String title;
                @XmlElement(required = true)
                protected String location;
                @XmlAttribute(name = "id")
                protected Byte id;

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the location property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocation() {
                    return location;
                }

                /**
                 * Sets the value of the location property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocation(String value) {
                    this.location = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setId(Byte value) {
                    this.id = value;
                }

            }

        }

    }

}

