//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 04:02:04 PM WET 
//


package xmlrest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlrest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlrest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListCourses }
     * 
     */
    public ListCourses createListCourses() {
        return new ListCourses();
    }

    /**
     * Create an instance of {@link ListCourses.Courses }
     * 
     */
    public ListCourses.Courses createListCoursesCourses() {
        return new ListCourses.Courses();
    }

    /**
     * Create an instance of {@link ListCourses.Courses.Materials }
     * 
     */
    public ListCourses.Courses.Materials createListCoursesCoursesMaterials() {
        return new ListCourses.Courses.Materials();
    }

    /**
     * Create an instance of {@link ListCourses.Courses.Materials.Material }
     * 
     */
    public ListCourses.Courses.Materials.Material createListCoursesCoursesMaterialsMaterial() {
        return new ListCourses.Courses.Materials.Material();
    }

}

