
package clientws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriberServiceService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8081/subs?wsdl")
public class SubscriberServiceService
    extends Service
{

    private final static URL SUBSCRIBERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIBERSERVICESERVICE_EXCEPTION;
    private final static QName SUBSCRIBERSERVICESERVICE_QNAME = new QName("http://ws/", "SubscriberServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/subs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSCRIBERSERVICESERVICE_WSDL_LOCATION = url;
        SUBSCRIBERSERVICESERVICE_EXCEPTION = e;
    }

    public SubscriberServiceService() {
        super(__getWsdlLocation(), SUBSCRIBERSERVICESERVICE_QNAME);
    }

    public SubscriberServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIBERSERVICESERVICE_QNAME, features);
    }

    public SubscriberServiceService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIBERSERVICESERVICE_QNAME);
    }

    public SubscriberServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIBERSERVICESERVICE_QNAME, features);
    }

    public SubscriberServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriberService
     */
    @WebEndpoint(name = "SubscriberServicePort")
    public SubscriberService getSubscriberServicePort() {
        return super.getPort(new QName("http://ws/", "SubscriberServicePort"), SubscriberService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberService
     */
    @WebEndpoint(name = "SubscriberServicePort")
    public SubscriberService getSubscriberServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "SubscriberServicePort"), SubscriberService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIBERSERVICESERVICE_EXCEPTION!= null) {
            throw SUBSCRIBERSERVICESERVICE_EXCEPTION;
        }
        return SUBSCRIBERSERVICESERVICE_WSDL_LOCATION;
    }

}
