
package clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriberService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delSub", targetNamespace = "http://ws/", className = "clientws.DelSub")
    @ResponseWrapper(localName = "delSubResponse", targetNamespace = "http://ws/", className = "clientws.DelSubResponse")
    public String delSub(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSubs", targetNamespace = "http://ws/", className = "clientws.ListSubs")
    @ResponseWrapper(localName = "listSubsResponse", targetNamespace = "http://ws/", className = "clientws.ListSubsResponse")
    public String listSubs();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSub", targetNamespace = "http://ws/", className = "clientws.CreateSub")
    @ResponseWrapper(localName = "createSubResponse", targetNamespace = "http://ws/", className = "clientws.CreateSubResponse")
    public String createSub(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
